GET http://127.0.0.1:5000/api/v2/projects HTTP/1.1

###
POST http://127.0.0.1:5000/api/v2/project HTTP/1.1
content-type: application/json

{
    "id": 0,
    "name": "Project Name",
    "owner": "some_random_address",
    "traitTypes": ["Trait Type 1", "Trait Type 2"]
}

###
GET http://127.0.0.1:5000/api/v2/project/0 HTTP/1.1

###
POST http://127.0.0.1:5000/api/v2/collection HTTP/1.1
content-type: application/json

{
    "id": 0,
    "name": "Project Name",
    "projectId": "1",
    "royalties": 80,
    "maxInvocation": 100,
    "manager": "some_random_address",
    "assetType": 0,
    "paused": true
}

###
GET http://127.0.0.1:5000/api/v2/collection/1 HTTP/1.1

###
PATCH  http://127.0.0.1:5000/api/v2/project HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "name": "New Project Name"
}

###
PATCH  http://127.0.0.1:5000/api/v2/collection HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "name": "New Collection Name"
}

###
POST  http://127.0.0.1:5000/api/v2/token HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "name": "New Collection Name",
    "collectionId": 1,
    "maxSupply": 100,
    "priceInWei": 1000,
    "traitType": "Weapon" 
}

###
PATCH  http://127.0.0.1:5000/api/v2/master HTTP/1.1
Content-Type: application/json

{
    "traitIds": [0, 1, 2],
    "masterId": 7
}
