GET http://127.0.0.1:5000/2 HTTP/1.1

###

POST http://127.0.0.1:5000/token HTTP/1.1
content-type: application/json

{
    "description": "description", 
    "external_url": "external_url", 
    "image": "image", 
    "name": "name", 
    "attributes": [{"trait_type": "token type", "value": 1}, {"trait_type": "trait type", "value": "armour"}]
}
###s

GET http://127.0.0.1:5000/whitelisted/0xe93F7bAd98e3742cE5c046e58F7084165243725a HTTP/1.1

###

PATCH http://localhost:5000/token HTTP/1.1
content-type: application/json

{
    "traitIds": ["1","2"],
    "masterId": "42"
}

###

GET http://127.0.0.1:5000/tokens?tokenIds=["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11","12", "13", "14", "15"] HTTP/1.1